# This file was generated by GoReleaser. DO NOT EDIT.
cask "bkt2gh" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_amd64.tar.gz"
      sha256 "108cc08bfc71d8d27673122b47296b476e6fbc6dd1238a12b20478f72b93806d"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_arm64.tar.gz"
      sha256 "34b51db6ad6160f74a7fa1fc0565d5f5b2e3248ac62f0f88e6242c95f60d2197"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_amd64.tar.gz"
      sha256 "4c4b974b15d7ba3cb11c30a5d9349529a228e9ca7432443b67cbd3a2f9232424"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_arm64.tar.gz"
      sha256 "92b4f78c6f0ebe4d448232b55b2c6c4208284fefc5927ff4fb3cbc74428e4fe7"
    end
  end

  name "bkt2gh"
  desc "CLI for migrating Bitbucket Cloud repositories to GitHub"
  homepage "https://github.com/ludens/bkt-to-gh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bkt2gh"

  # No zap stanza required

  caveats <<~EOS
    Run `bkt2gh configure` before your first migration.
  EOS
end
