# This file was generated by GoReleaser. DO NOT EDIT.
cask "bkt2gh" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_amd64.tar.gz"
      sha256 "4c290f1f3843cfaa8dd989092d92d2e8f81426dfd1f2052c525cd84e08f6a4a9"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_arm64.tar.gz"
      sha256 "ebec6b88800b6376b85194303026655e94104bd96b3765044f841a3ff0b05966"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_amd64.tar.gz"
      sha256 "25802667c5ff7f362ff61e08ab04b519aab8ac355142e3d460e5b83f99c31bee"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_arm64.tar.gz"
      sha256 "2856d3d9683e975dfe1045c318972b9769993a18fe8209f34c04b112af8481eb"
    end
  end

  name "bkt2gh"
  desc "CLI for migrating Bitbucket Cloud repositories to GitHub"
  homepage "https://github.com/ludens/bkt-to-gh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bkt2gh"

  # No zap stanza required

  caveats <<~EOS
    Run `bkt2gh configure` before your first migration.
  EOS
end
