# This file was generated by GoReleaser. DO NOT EDIT.
cask "bkt2gh" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_amd64.tar.gz"
      sha256 "2f2fbe08f5c7aa581c7dfcba0f49fdb94e0f2dd665a115cb02fc0b6b916ee0aa"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_darwin_arm64.tar.gz"
      sha256 "262218599fa79d9dabe49d228e30f20fb1d7ee3e58e609d1a1995ed2f7f22f93"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_amd64.tar.gz"
      sha256 "bd9a833c397e98633f7e00bc604f4e5cfe6730ed1040dd846ef81c8276dabbd7"
    end
    on_arm do
      url "https://github.com/ludens/bkt-to-gh/releases/download/v#{version}/bkt2gh_#{version}_linux_arm64.tar.gz"
      sha256 "8e4fb8ad082f5c330c187271227373fe26cc905de4bfc44ab934ac1b0ed17549"
    end
  end

  name "bkt2gh"
  desc "CLI for migrating Bitbucket Cloud repositories to GitHub"
  homepage "https://github.com/ludens/bkt-to-gh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bkt2gh"

  # No zap stanza required

  caveats <<~EOS
    Run `bkt2gh configure` before your first migration.
  EOS
end
